on:
  push:
    branches:
      - main
env: 
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
  BUILD_NUMBER: 0.${{ github.run_number }}.${{ github.run_attempt }}-aws/integration
  
jobs:
 init:
    name: Get AWS Credentials
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:

      - uses: actions/checkout@v2

      - uses: aws-actions/configure-aws-credentials@v1
        with: 
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-west-2
